#!/usr/bin/env bash

# Transfer a file to a remote device via SCP.
#
# Dependencies:
#   This script depends on the `set_ssh_options` script to set SSH options.
#   DEVICE_IP and DEVICE_USER must be set in the environment.
#
# Usage:
#   `_put <local_file> <remote_file>`
#   Or source it in another script and call
#   `put_function <local_file> <remote_file>`

put_function() {
    source "$(dirname "$BASH_SOURCE")/set_ssh_options"
    scp $SSH_OPTS $1 ${DEVICE_USER:-ubuntu}@$DEVICE_IP:$2
}

# Check if the script is being sourced or executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    put_function "$@"
fi
