#!/usr/bin/env bash

# Transfer a file to a remote device via SCP.
#
# Description:
#
# The IP of the device is provided by the environment variable DEVICE_IP,
# which must be set. The user name on the remote device is `ubuntu`
# by default, unless provided by the environment variable DEVICE_USER.
#
# This script depends on the `set_ssh_options` script to set SSH options.
#
# Return value:
#
# 0 if the copy operation is successful or >0 in case of an error.

usage() {
    echo "Usage: $(basename $0) <source> ... <target>"
}

parse_args() {
    if [ $# -lt 2 ]; then
        usage
        echo "Error: <source> and/or <target> not specified"
        exit 1
    fi

    # The target is the last argument
    export TARGET=${@: -1}
    [[ "$TARGET" != "--" ]] || unset TARGET

    # Remove the target from the list by slicing the arguments array
    SOURCES_ARRAY=("${@:1:$#-1}")
    export SOURCES="${SOURCES_ARRAY[@]}"
}


if [ -z $DEVICE_IP ]; then
    echo "Error $(basename $0): Environment variable DEVICE_IP not set"
    exit 1
fi

parse_args $@
source "$(dirname "$BASH_SOURCE")/defs/ssh_options"
scp $SSH_OPTS $SOURCES ${DEVICE_USER:-ubuntu}@$DEVICE_IP:$TARGET
