#!/usr/bin/env bash

# Run a command on a remote device via SSH.
#
# Dependencies:
#   This script depends on the `set_ssh_options` script to set SSH options.
#   DEVICE_IP and DEVICE_USER must be set in the environment.
#
# Usage:
#   `_run <command> [command_args ...]`
#   Or source it in another script and call
#   `run_function <command> [command_args ...]`

run_function() {
    source "$(dirname "$BASH_SOURCE")/set_ssh_options"
    ssh $SSH_OPTS ${DEVICE_USER:-ubuntu}@$DEVICE_IP "$@"
}

# Check if the script is being sourced or executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    run_function "$@"
fi
