#!/usr/bin/env bash

# Run a command on a remote device via SSH.
#
# Description:
#
# The IP of the device is provided by the environment variable DEVICE_IP,
# which must be set. The user name on the remote device is `ubuntu`
# by default, unless provided by the environment variable DEVICE_USER.
#
# This script depends on the `set_ssh_options` script to set SSH options.
#
# Return value:
#
# The value returned by the command on the remote device, or 255 in case
# of an ssh error

usage() {
    echo "Usage: $(basename $0) <command>"
}

if [ -z $DEVICE_IP ]; then
    echo "Error: Environment variable DEVICE_IP not set"
    exit 1
fi

if [ $# -lt 1 ]; then
    usage
    echo "Error: <command> not specified"
    exit 1
fi

source "$(dirname "$BASH_SOURCE")/defs/ssh_options"
ssh $SSH_OPTS ${DEVICE_USER:-ubuntu}@$DEVICE_IP "$@"
