#!/usr/bin/env bash

# Run a command on a remote device via SSH, retrying in case of errors
#
# Description:
#
# This script is identical to `_run`, only it retries the <command>
# up to 20 times with a 30-second delay.
#
# Return value:
#
# The value returned by the command on the remote device, or 255 in case
# of an ssh error

usage() {
    echo "Usage: $(basename ${BASH_SOURCE[0]}) <command>"
}

parse_args() {
    if [ $# -lt 1 ]; then
        usage
        echo "Error: <command> not specified"
        exit 1
    fi
}


parse_args $@

retry --times 20 --delay 30 -- \
    _run "$@"

result=$?
if [ $result -gt 0 ]; then
    echo "Error: unable to complete $(basename ${BASH_SOURCE[0]}) $@"
fi
exit $result
