#!/usr/bin/env bash

# Check if a remote device is fully up and running.
#
# Description:
#
# The script runs `systemctl is-system-running` on the remote device.
# It succeeds "when the system is fully up and running, meaning
# not in startup, shutdown or maintainance mode."
#
# There are cases when `degraded` (rather than `running`), which signifies
# a failure to start certain services, is also acceptable as a state, in
# which case the `--allow-degraded` command-line flag should be provided.
#
# Return value:
# 
# The return value of `systemctl is-system-running`
# https://www.man7.org/linux/man-pages/man1/systemctl.1.html
# or 255 in case of an ssh failure

usage() {
    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--allow-degraded]"
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --allow-degraded)
            ALLOW_DEGRADED="(degraded allowed)"
            ;;
        *)
            usage
            echo "Error: Invalid argument $1"
            exit 1
            ;;
    esac
    shift
done

echo "Checking if ${DEVICE_IP:-device} is fully up and running $ALLOW_DEGRADED"
RESULT=$(_run systemctl is-system-running)
STATUS=$?
[ -n "$RESULT" ] && echo $RESULT
# check returned result and propagate `_run`'s exit status if not successful
if [ -z "$ALLOW_DEGRADED" ]; then
    [[ "$RESULT" =~ ^running ]] || exit $STATUS
else
    [[ "$RESULT" =~ ^(running|degraded) ]] || exit $STATUS
fi