#!/bin/bash

# Perform connections between the Checkbox snaps on matching interfaces

usage() {
    echo "Usage: $(basename ${BASH_SOURCE[0]})"
}

connect() {
    # use the snapd API on the device to collect snap connection data
    # (equivalent to `_run snap connections --all` but with detailed JSON output)
    SNAP_CONNECTION_DATA=$(
        printf 'GET /v2/connections?select=all HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' |
        _run nc -U /run/snapd.socket |
        grep -o '{.*}'
    )
    # process the snap connection data and retrieve the possible connections
    CONNECTIONS=$(echo $SNAP_CONNECTION_DATA | snap_connections)
    # perform the connections one-by-one
    while IFS='/' read -r PLUG SLOT; do
        echo "Connecting $PLUG to $SLOT"
        # input from /dev/null prevents ssh from consuming the standard input
        _run sudo snap connect $PLUG $SLOT < /dev/null
    done <<< "$CONNECTIONS"
}

set -e

if [ "$#" -gt 0 ]; then
    usage
    echo "Error: Unknown arguments $@"
    exit 1
fi

log "Auto-detecting possible snap connections"
connect