#!/usr/bin/env bash

# Install Checkbox from repo, matching a specific version
#
# Description:
#
# The script clones the Checkbox repo and then uses the `checkout_to_version`
# tool in order to checkout and install a version of Checkbox that matches
# a specific version provided as an argument.
#
# The second argument, the `tools_path` is only necessary in order to locate
# the `checkout_to_version` tool. It can be removed if that tool is installed
# (it is currently not).

usage() {
    echo "Usage: $(basename $0) <version> <tools_path>"
}

if [ $# -ne 2 ]; then
    usage
    echo "Error: incorrect number of arguments"
    exit 1
fi

VERSION=$1
TOOLS_PATH=$2

# clone Checkbox repo
git clone --filter=tree:0 https://github.com/canonical/checkbox.git > /dev/null

# checkout commit to match the required version
$TOOLS_PATH/version-published/checkout_to_version.py ~/checkbox "$VERSION"

# install checkbox from source
(cd checkbox/checkbox-ng; sudo python3 setup.py install > /dev/null)
sudo rm -rf checkbox
