#!/usr/bin/env bash

usage() {
    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--no-update] -- <apt-get install arguments>"
}

parse_args() {
    while [[ "$#" -gt 0 ]]; do
        case $1 in
            --no-update)
                export NO_UPDATE="true"
                ;;
            --)
                shift
                export INSTALL_ARGS="$@"
                break
                ;;
            *)
                usage
                echo "Error: Invalid argument $1"
                exit 1
                ;;
        esac
        shift
    done
}


parse_args $@

wait_for_packages_complete
result=$?
if [ $result -gt 0 ]; then
    echo "Error: unable to complete $(basename ${BASH_SOURCE[0]})"
    exit $result
fi

[ -n "$NO_UPDATE" ] || sudo apt-get -qq update
sudo DEBIAN_FRONTEND=noninteractive apt-get -qqy install -o Dpkg::Options::="--force-confdef" $INSTALL_ARGS
