#!/usr/bin/env bash

# Install Checkbox from repo, matching a specific version.
#
# Description:
#
# The script clones the Checkbox repo and then uses the `checkout_to_version`
# tool in order to checkout and install a version of Checkbox that matches
# a specific version provided as an argument.
#
# The second argument, the `tools_path` is necessary in order to locate the
# `checkout_to_version` tool. It can be removed if that tool is installed (it
# is currently not). The argument is also not required if TOOLS_PATH is set.

usage() {
    echo "Usage: $(basename $0) <version> [<tools_path>]"
}

if [ $# -gt 2 ]; then
    usage
    echo "Error: Too many arguments"
    exit 1
fi

if [ $# -lt 1 ]; then
    usage
    echo "Error: <version> not specified"
    exit 1
fi

VERSION=$1

if [ $# -eq 2 ]; then
    TOOLS_PATH=$2
elif [ -z "$TOOLS_PATH" ]; then
    usage
    echo "Error: <tools_path> not specified and TOOLS_PATH not set"
    exit 1
fi

# clone Checkbox repo
git clone --filter=tree:0 https://github.com/canonical/checkbox.git > /dev/null

# checkout commit to match the required version
$TOOLS_PATH/version-published/checkout_to_version.py ~/checkbox "$VERSION"

# install checkbox from source
pipx install checkbox/checkbox-ng
pipx inject checkbox-ng "urwid<3"
sudo rm -rf checkbox
