#!/usr/bin/env bash

if [ "$1" = "--warn" ]; then
    TAG=WARN
elif [ "$1" = "--error" ]; then
    TAG=ERROR
else
    TAG=INFO
fi

CALLER=$(basename $(ps -o command= $PPID | cut -d ' ' -f 2))
echo "$(date '+%Y-%m-%d %T') [$TAG] $CALLER: $*"
