#!/usr/bin/env bash

# Update the Zapper snap (and firmware) if needed
#
# Description:
#
# If a Zapper is part of the setup, refresh the snap
# to the target channel (default is `beta`), upgrade firmware
# and wait until the add-ons are recognized.

export DEVICE_IP=$ZAPPER_IP
export DEVICE_PWD=${ZAPPER_PWD:-insecure}

usage() {
    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--channel]"
}

CHANNEL=beta
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --channel)
            CHANNEL=$2
            shift
            ;;
        *)
            usage
            echo "Error: Invalid argument $1"
            exit 1
            ;;
    esac
    shift
done

check_for_device_ip >> /dev/null || exit 0

message=$(_run sudo snap refresh zapper --amend --channel $CHANNEL 2>&1)
if echo "$message" | grep -q 'no updates available'; then
    echo "Snap was up-to-date, restarting the service instead..."
    _run sudo snap restart zapper
fi

# Update only the mainboard firmware. The add-on firmware is rarely updated,  
# and it's safer to do it manually for the time being.
_run zapper firmware update -y --allow-older --component-type MAINBOARD
