#!/usr/bin/env bash

# Update the Zapper snap (and firmware) if needed
#
# Description:
#
# If a Zapper is part of the setup, refresh the snap
# to the target channel (default is `beta`), upgrade firmware
# and wait until the add-ons are recognized.

usage() {
    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--channel]"
}

CHANNEL=beta
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --channel)
            CHANNEL=$2
            shift
            ;;
        *)
            usage
            echo "Error: Invalid argument $1"
            exit 1
            ;;
    esac
    shift
done

# Running in a subshell to not exit with error like it normally would when failing
(source "$(dirname ${BASH_SOURCE[0]})/defs/check_for_zapper_ip" >> /dev/null)

message=$(_run_zapper sudo snap refresh zapper --amend --channel $CHANNEL 2>&1)
if echo "$message" | grep -q 'no updates available'; then
    echo "Snap was up-to-date, restarting the service instead..."
    _run_zapper sudo snap restart zapper
fi
wait_for_zapper_addons

message=$(_run_zapper zapper firmware update -y --allow-older)
if echo "$message" | grep -q 'update in progress'; then
    echo "Firmware(s) got upgraded, waiting again for the add-on discovery..."
    wait_for_zapper_addons
fi
