#!/usr/bin/env bash

# Install a specific kernel package (specified in the scenario file)
# and perform a dist-upgrade

check_for_scenario_file || exit 1
CONCRETE_KERNEL="$(scenario artifact.name)"

_run wait_for_packages_complete

_run install_packages --install-recommends $CONCRETE_KERNEL
_run wait_for_packages_complete

_run install_packages --dist-upgrade -- --allow-remove-essential
_run wait_for_packages_complete

_run sudo reboot
wait_for_ssh --allow-degraded
