#!/usr/bin/env bash

# Install a specific kernel package and perform a dist-upgrade

CONCRETE_KERNEL="$1"

_run wait_for_packages_complete

log "Installing $CONCRETE_KERNEL"
_run install_packages --install-recommends $CONCRETE_KERNEL
_run wait_for_packages_complete

log "Running a dist-upgrade"
_run install_packages --dist-upgrade -- --allow-remove-essential
_run wait_for_packages_complete

log "Rebooting for changes to take effect"
_run sudo reboot
wait_for_ssh --allow-degraded
