#!/usr/bin/env bash

# Wait until SSH is available on a remote device.
#
# This works by repeated attempts to connect to the device via SSH
# until successful or until a timeout is reached.
#
# Dependencies:
#   This script depends on the `_run` scriptlet
#
# Usage:
#   `wait_for_ssh [attempts]`

wait_for_ssh_function() {
    local base=$(dirname "$BASH_SOURCE")
    local attempts=${1:-20} # If no argument is passed, default to 20
    local loopcnt=0
    until timeout 10 $base/_run /bin/true
    do
        echo "Testing to see if system is back up"
        loopcnt=$((loopcnt+1))
        if [ $loopcnt -gt $attempts ]; then
            echo "ERROR: Timeout waiting for ssh!"
            return 1
        fi
        sleep 30
    done
    return 0
}

# Check if the script is being sourced or executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    wait_for_ssh_function "$@"
fi
