#!/usr/bin/env bash
#
# Wait until package operations (apt, dpkg) are complete
#
# See `check_for_packages` (which is repeatedly called here)
# for details.
#
# There is a global timeout on the wait operation. In the case
# of a timeout, all processes relevant to package handling (apt,
# apt-get, dpkg) are killed.
#
# Return value:
# 
# 0 if `check_for_packages` is successful
# 1 if `check_for_packages` cannot be executed or is unsuccesful on the last retry
# >=124 in case of a timeout
# https://manpages.ubuntu.com/manpages/focal/man1/retry.1.html
# https://man7.org/linux/man-pages/man1/timeout.1.html

timeout 10m retry --delay 1 -- check_for_packages

result=$?
if [ $result -ge 124 ]; then
    echo "Unable to complete $(basename $0). Killing apt, apt-get, and dpkg processes."
    sudo pkill -x "apt|apt-get|dpkg"
fi
exit $result
