#!/usr/bin/env bash

# Wait for a specific snap change on a remote device to complete
# 
# See `check_for_snap_complete_id` (which is repeatedly called here)
# for details
#
# Return value:
# 
# 0 if `check_for_snap_change_id` is successful or 1 otherwise

usage() {
    echo "Usage: $(basename $0) <change-id>"
}

TIMES=20
DELAY=10
CHANGE_ID=
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --times)
            TIMES=$2
            shift
            ;;
        --delay)
            DELAY=$2
            shift
            ;;
        *)
            if [ -n "$CHANGE_ID" ]; then
                usage
                echo "Error: Invalid argument $1"
                exit 1
            fi
            CHANGE_ID=$1
            ;;
    esac
    shift
done

if [ -z "$CHANGE_ID" ]; then
    usage
    echo "Error: <change-id> not specified"
    exit 1
fi

retry --times $TIMES --delay $DELAY -- \
check_for_snap_change_id $CHANGE_ID

RESULT=$?
if [ $RESULT -gt 0 ]; then
    echo "Error: unable to complete $(basename $0) for change ID: $CHANGE_ID"
fi
exit $RESULT
