#!/usr/bin/env bash
#
# Wait until package operations (apt, dpkg) are complete
#
# See `check_for_packages_complete` (which is repeatedly called here)
# for details.
#
# There is a global timeout on the wait operation. In the case
# of a timeout, all processes relevant to package handling (apt,
# apt-get, dpkg) are killed.
#
# Return value:
# 
# 0 if `check_for_packages_complete` is successful
# 1 if `check_for_packages_complete` cannot be executed or is unsuccesful on the last retry
# >=124 in case of a timeout
# https://manpages.ubuntu.com/manpages/focal/man1/retry.1.html
# https://man7.org/linux/man-pages/man1/timeout.1.html

usage() {
    echo "Usage: $(basename ${BASH_SOURCE[0]})"
}

parse_args() {
    if [ $# -gt 0 ]; then
        usage
        echo "Error: invalid arguments $@"
        exit 1
    fi
}

parse_args $@

timeout 10m retry --delay 5 -- check_for_packages_complete

result=$?
if [ $result -ge 124 ]; then
    echo "Unable to complete $(basename ${BASH_SOURCE[0]}) (timeout). Killing apt, apt-get, and dpkg processes."
    sudo pkill -x "apt|apt-get|dpkg"
fi
exit $result
