#!/usr/bin/env bash

# Wait for all snap operations on a remote device to complete.
#
# This works by using SSH to query the snap changes on the device and check
# for any ongoing operations.
# The script will retry up to 40 times, with a 30-second sleep between attempts.
#
# Dependencies:
#   This script depends on the `_run` scriptlet
#
# Usage:
#   `wait_for_snap_complete <command> [command_args ...]`

wait_for_snap_complete_function() {
    local loopcnt=0
    until [ $loopcnt -gt 40 ]
    do
        loopcnt=$((loopcnt+1))
        changes="$(_run 'sudo snap changes')"
        echo Checking for all snap operations to complete...
        echo $changes
        if [ -n "$changes" ] &&
            [[ "$changes" != *"Doing"* ]] &&
            [ "$(_run echo true)" = "true" ]; then
            done="true"
            break
        fi
        sleep 30
    done
    if [ -z "$done" ]; then
        echo "ERROR: Timeout waiting for snap operations!"
        return 1
    fi
    set -x
    return 0
}

# Check if the script is being sourced or executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  wait_for_snap_complete_function "$@"
fi
