#!/usr/bin/env bash

# Busy loop around the Zapper add-on discovery process
#
# Description:
#
# Once the Zapper service starts, the Zapper starts a
# discovery process to recognize every add-on connected
# to the add-on bus. This scriptlet polls the zapper
# add-on list until the length is stable for 3 consecutive
# iterations.

export DEVICE_IP=$ZAPPER_IP
export DEVICE_PWD=${ZAPPER_PWD:-insecure}

previous_addon_count=-1
stable_count=0
max_stable_checks=3
while true; do
    current_addon_count=$(_run zapper addon list 2> /dev/null | wc -l)
    if [[ "$current_addon_count" -eq "$previous_addon_count" ]]; then
      ((stable_count++))
    else
      stable_count=0
    fi

    if [[ "$stable_count" -ge "$max_stable_checks" ]]; then
      break
    fi

    previous_addon_count="$current_addon_count"
done
