#!/usr/bin/env bash

# Install package `psmisc` if `fuser` is not already available

# determine if fuser is already available
sudo which fuser > /dev/null 

# install psmisc if required
RESULT=$?
if [ ! "$RESULT" -eq 0 ]; then
    echo "Installing fuser (psmisc)"
    wait_for_packages_complete --no-files-check && \
    install_packages psmisc
fi