#!/usr/bin/env bash
#
# Determine if any path in a set of predefined paths is in PATH and display it.
#
# Description:
# 
# This script is meant to be run on the device, in order to determine where
# to place a small set of scripts that need to be accessible from the PATH.

DIRECTORIES=(/usr/local/bin /usr/bin /opt/bin /bin /snap/bin)
for DIRECTORY in "${DIRECTORIES[@]}"; do
    if [[ ":$PATH:" = *":$DIRECTORY:"* ]] && [ -d "$DIRECTORY" ]; then
        # Get the mount point of the directory
        POINT=$(df --output=target "$DIRECTORY" | tail -1)
        # Check if the mounted filesystem is writable
        # (necessary for core images)
        if mount | grep -w "$POINT" | grep -q 'rw,'; then
            echo $DIRECTORY
            exit 0
        fi
    fi
done
